#!/bin/bash

# Dependencies
mvn install:install-file \
   -Dfile=./lib/jflex-1.8.2/lib/jflex-full-1.8.2.jar \
   -DgroupId=de.jflex \
   -DartifactId=jflex \
   -Dversion=1.8.2 \
   -Dpackaging=jar \
   -DgeneratePom=true
mvn install:install-file \
   -Dfile=./lib/args4j-2.33.jar \
   -DgroupId=args4j \
   -DartifactId=args4j\
   -Dversion=2.33 \
   -Dpackaging=jar \
   -DgeneratePom=true
# Create jar
mvn package

rm -f src/main/java/mtm68/lexer/Lexer.java 
./lib/jflex-1.8.2/bin/jflex src/main/java/mtm68/lexer/lexer.flex 

## Create executable
echo "java -cp target/xic-0.0.1-SNAPSHOT.jar mtm68.Main \$@" > xic
chmod +x xic
