#!/bin/bash
ROOT_DIR=`dirname "$0"`

rm -f ${ROOT_DIR}/src/main/java/mtm68/lexer/Lexer.java 
${ROOT_DIR}/lib/jflex-1.8.2/bin/jflex ${ROOT_DIR}/src/main/java/mtm68/lexer/lexer.flex 

# Dependencies
mvn install:install-file \
   -Dfile=${ROOT_DIR}/lib/jflex-1.8.2/lib/jflex-full-1.8.2.jar \
   -DgroupId=de.jflex \
   -DartifactId=jflex \
   -Dversion=1.8.2 \
   -Dpackaging=jar \
   -DgeneratePom=true
# Create jar
mvn package -Dmaven.repo.local=${ROOT_DIR}/lib package

## Create executable
echo "java -cp ${ROOT_DIR}/target/xic-0.0.1-SNAPSHOT.jar mtm68.Main \$@" > xic
chmod +x xic
