
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package mtm68.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPEN_PAREN = 20;
  public static final int IXI = 6;
  public static final int MULT = 32;
  public static final int UMINUS = 44;
  public static final int INTEGER = 5;
  public static final int INT = 14;
  public static final int CLOSE_SQUARE = 19;
  public static final int CHARACTER = 4;
  public static final int AND = 42;
  public static final int SEMICOLON = 26;
  public static final int LT = 36;
  public static final int USE = 8;
  public static final int CLOSE_PAREN = 21;
  public static final int OR = 43;
  public static final int BOOL = 15;
  public static final int COMMA = 27;
  public static final int CLASS = 45;
  public static final int DIV = 33;
  public static final int GEQ = 39;
  public static final int OPEN_SQUARE = 18;
  public static final int OPEN_CURLY = 22;
  public static final int IF = 9;
  public static final int EXCLAMATION = 24;
  public static final int THIS = 47;
  public static final int DOT = 49;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int XI = 7;
  public static final int TRUE = 16;
  public static final int NEW = 48;
  public static final int error = 1;
  public static final int ADD = 30;
  public static final int EQEQ = 40;
  public static final int MOD = 34;
  public static final int NEQ = 41;
  public static final int EQ = 28;
  public static final int COLON = 25;
  public static final int CLOSE_CURLY = 23;
  public static final int ELSE = 10;
  public static final int WHILE = 11;
  public static final int HIGH_MULT = 35;
  public static final int EXTENDS = 46;
  public static final int LEQ = 37;
  public static final int UNDERSCORE = 29;
  public static final int STRING = 3;
  public static final int FALSE = 17;
  public static final int GT = 38;
  public static final int SUB = 31;
  public static final int LENGTH = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "STRING",
  "CHARACTER",
  "INTEGER",
  "IXI",
  "XI",
  "USE",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "LENGTH",
  "INT",
  "BOOL",
  "TRUE",
  "FALSE",
  "OPEN_SQUARE",
  "CLOSE_SQUARE",
  "OPEN_PAREN",
  "CLOSE_PAREN",
  "OPEN_CURLY",
  "CLOSE_CURLY",
  "EXCLAMATION",
  "COLON",
  "SEMICOLON",
  "COMMA",
  "EQ",
  "UNDERSCORE",
  "ADD",
  "SUB",
  "MULT",
  "DIV",
  "MOD",
  "HIGH_MULT",
  "LT",
  "LEQ",
  "GT",
  "GEQ",
  "EQEQ",
  "NEQ",
  "AND",
  "OR",
  "UMINUS",
  "CLASS",
  "EXTENDS",
  "THIS",
  "NEW",
  "DOT"
  };
}

