
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

package mtm68.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ADD = 29;
  public static final int UNDERSCORE = 28;
  public static final int LENGTH = 11;
  public static final int LT = 35;
  public static final int error = 1;
  public static final int CLOSE_CURLY = 22;
  public static final int INT = 12;
  public static final int RETURN = 10;
  public static final int MULT = 31;
  public static final int SEMICOLON = 25;
  public static final int ELSE = 8;
  public static final int CHARACTER = 4;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int IF = 7;
  public static final int INTEGER = 5;
  public static final int OPEN_CURLY = 21;
  public static final int COMMA = 26;
  public static final int SUB = 30;
  public static final int MOD = 33;
  public static final int OR = 42;
  public static final int USE = 6;
  public static final int HIGH_MULT = 34;
  public static final int DOT = 16;
  public static final int TRUE = 14;
  public static final int COLON = 24;
  public static final int EQ = 27;
  public static final int GT = 37;
  public static final int DIV = 32;
  public static final int OPEN_SQUARE = 17;
  public static final int GEQ = 38;
  public static final int OPEN_PAREN = 19;
  public static final int BOOL = 13;
  public static final int EXCLAMATION = 23;
  public static final int AND = 41;
  public static final int EQEQ = 39;
  public static final int STRING = 3;
  public static final int CLOSE_SQUARE = 18;
  public static final int LEQ = 36;
  public static final int WHILE = 9;
  public static final int FALSE = 15;
  public static final int CLOSE_PAREN = 20;
  public static final int NEQ = 40;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "STRING",
  "CHARACTER",
  "INTEGER",
  "USE",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "LENGTH",
  "INT",
  "BOOL",
  "TRUE",
  "FALSE",
  "DOT",
  "OPEN_SQUARE",
  "CLOSE_SQUARE",
  "OPEN_PAREN",
  "CLOSE_PAREN",
  "OPEN_CURLY",
  "CLOSE_CURLY",
  "EXCLAMATION",
  "COLON",
  "SEMICOLON",
  "COMMA",
  "EQ",
  "UNDERSCORE",
  "ADD",
  "SUB",
  "MULT",
  "DIV",
  "MOD",
  "HIGH_MULT",
  "LT",
  "LEQ",
  "GT",
  "GEQ",
  "EQEQ",
  "NEQ",
  "AND",
  "OR"
  };
}

