
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package mtm68.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPEN_PAREN = 22;
  public static final int IXI = 8;
  public static final int MULT = 34;
  public static final int UMINUS = 46;
  public static final int INTEGER = 5;
  public static final int INT = 16;
  public static final int CLOSE_SQUARE = 21;
  public static final int CHARACTER = 4;
  public static final int AND = 44;
  public static final int SEMICOLON = 28;
  public static final int LT = 38;
  public static final int USE = 10;
  public static final int CLOSE_PAREN = 23;
  public static final int OR = 45;
  public static final int BOOL = 17;
  public static final int COMMA = 29;
  public static final int FUNAPP = 6;
  public static final int DIV = 35;
  public static final int GEQ = 41;
  public static final int OPEN_SQUARE = 20;
  public static final int OPEN_CURLY = 24;
  public static final int IF = 11;
  public static final int EXCLAMATION = 26;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int XI = 9;
  public static final int TRUE = 18;
  public static final int error = 1;
  public static final int ADD = 32;
  public static final int EQEQ = 42;
  public static final int MOD = 36;
  public static final int NEQ = 43;
  public static final int EQ = 30;
  public static final int COLON = 27;
  public static final int CLOSE_CURLY = 25;
  public static final int ELSE = 12;
  public static final int INDEX = 7;
  public static final int WHILE = 13;
  public static final int HIGH_MULT = 37;
  public static final int LEQ = 39;
  public static final int UNDERSCORE = 31;
  public static final int STRING = 3;
  public static final int FALSE = 19;
  public static final int GT = 40;
  public static final int SUB = 33;
  public static final int LENGTH = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "STRING",
  "CHARACTER",
  "INTEGER",
  "FUNAPP",
  "INDEX",
  "IXI",
  "XI",
  "USE",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "LENGTH",
  "INT",
  "BOOL",
  "TRUE",
  "FALSE",
  "OPEN_SQUARE",
  "CLOSE_SQUARE",
  "OPEN_PAREN",
  "CLOSE_PAREN",
  "OPEN_CURLY",
  "CLOSE_CURLY",
  "EXCLAMATION",
  "COLON",
  "SEMICOLON",
  "COMMA",
  "EQ",
  "UNDERSCORE",
  "ADD",
  "SUB",
  "MULT",
  "DIV",
  "MOD",
  "HIGH_MULT",
  "LT",
  "LEQ",
  "GT",
  "GEQ",
  "EQEQ",
  "NEQ",
  "AND",
  "OR",
  "UMINUS"
  };
}

