package mtm68.ir.cfg;

import java.io.IOException;
import java.io.Writer;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

import edu.cornell.cs.cs4120.ir.IRExpr;
import edu.cornell.cs.cs4120.ir.IRFuncDefn;
import edu.cornell.cs.cs4120.ir.IRMove;
import edu.cornell.cs.cs4120.ir.IRSeq;
import edu.cornell.cs.cs4120.ir.IRStmt;
import edu.cornell.cs.cs4120.ir.IRTemp;
import mtm68.assem.cfg.Graph;
import mtm68.assem.cfg.Graph.Node;
import mtm68.ir.cfg.IRCFGBuilder.IRData;
import mtm68.util.SetUtils;

public class ReachingDefns {

	private Graph<IRData<ReachingData>> graph;
	private IRCFGBuilder<ReachingData> builder;
	
	private IRFuncDefn ir;

	public ReachingDefns(IRFuncDefn ir) {
		builder = new IRCFGBuilder<>();
		this.ir = ir;
	}
	
	public void performReachingDefnsAnalysis() {

		IRStmt body = ir.body();
	    List<IRStmt> stmts = ((IRSeq)body).stmts();

		graph = builder.buildIRCFG(stmts, ReachingData::new);
		List<Node> nodes = graph.getNodes();
		
		boolean changes = true;
		while (changes) {
			changes = false;
			
			for(Node node : nodes) {
				IRData<ReachingData> data = graph.getDataForNode(node);
				ReachingData flowData = data.getFlowData();
				
				
				Set<ReachingDefn> inOld = flowData.getIn();
				Set<ReachingDefn> outOld = flowData.getOut();
				
				Set<ReachingDefn> in = in(node);
				Set<ReachingDefn> out = out(node);
				
				flowData.setIn(in);
				flowData.setOut(out);
				
				changes = changes || (!inOld.equals(in) || !outOld.equals(out));
			}
		}
	}
	
	/**
	 * The set of definitions reaching a node.
	 * in[n] = definitions reaching on any edges into n.
	 */
	private Set<ReachingDefn> in(Node node) {
		Set<ReachingDefn> in = SetUtils.empty();
		for(Node pred : node.pred()) {
			Set<ReachingDefn> predData = graph.getDataForNode(pred)
											   .getFlowData()
											   .getOut();
			in = SetUtils.union(in, predData);
		}

		return in;
	}

	/**
	 * The set of available expressions on edges leaving node n.
	 * out[n] = gen[n] U (in(n) - kill(n))
	 */
	 private Set<ReachingDefn> out(Node n) {

		Set<ReachingDefn> gen = gen(n);
		Set<ReachingDefn> in = in(n);
		Set<ReachingDefn> kill = kill(n, in);
		
		Set<ReachingDefn> difference = SetUtils.difference(in, kill);
		 
		return SetUtils.union(gen , difference);
	 }
	 
	
	/**
	 * Definitions generated by a node.
	 * 
	 * For example,
	 * gen(x <- y) = node 
	 * else 	   = {}
	 */
	private Set<ReachingDefn> gen(Node node) {
		IRStmt ir = graph.getDataForNode(node).getIR();

		if (hasXGetsYForm(ir)) {
			return genXGetsY((IRMove)ir, node);

		} else {
			return SetUtils.empty();
		}
	}

	private Set<ReachingDefn> genXGetsY(IRMove mov, Node d) {
		IRTemp x = (IRTemp)mov.target();
		IRTemp y = (IRTemp)mov.source();
		
		ReachingDefn defn = new ReachingDefn(x, y, d);

		return SetUtils.elems(defn);
	}

	/**
	 * Expressions killed by a node that has facts l.
	 * 
	 * For example,
	 * kill(x <- e)    = defs(x)
	 * else		       = {}	
	 * 
	 * Where defs(x) denotes set of notes that define variable x
	 * or use variable x.
	 */
	private Set<ReachingDefn> kill(Node node, Set<ReachingDefn> l) {
		IRStmt ir = graph.getDataForNode(node).getIR();

		if (hasXGetsEForm(ir)) {
			return killXGetsE((IRMove)ir, l);

		} else {
			return SetUtils.empty();
		}
	}
	
	/**
	 * The subset of l that contains IRTemp t.
	 * @param ir of the form IRMove(IRTemp t, IRExpr)
	 */
	private Set<ReachingDefn> killXGetsE(IRMove ir, Set<ReachingDefn> l) {
		IRTemp temp = (IRTemp)ir.target();
		return l.stream()
				.filter(r -> r.x.containsExpr(temp) || r.y.containsExpr(temp))
				.collect(Collectors.toSet());
	}


	private boolean hasXGetsYForm(IRStmt ir) {
		return ir instanceof IRMove 
				&& ((IRMove)ir).target() instanceof IRTemp
				&& ((IRMove)ir).source() instanceof IRTemp;
	}
	
	private boolean hasXGetsEForm(IRStmt ir) {
		return ir instanceof IRMove 
				&& ((IRMove)ir).target() instanceof IRTemp
				&& ((IRMove)ir).source() instanceof IRExpr;
	}

	public Graph<IRData<ReachingData>> getGraph() {
		return graph;
	}
	
	public void showGraph(Writer writer) throws IOException {
		graph.show(writer, "AvailableExpressions", true, this::showAvailable);
	}
	
	public IRCFGBuilder<ReachingData> getBuilder() {
		return builder;
	}

	private String showAvailable(IRData<ReachingData> data) {
		Set<ReachingDefn> in = data.getFlowData().getIn();
		Set<ReachingDefn> out = data.getFlowData().getOut();
		IRStmt ir = data.getIR();

		StringBuilder sb = new StringBuilder();

		sb.append("In: ");
		sb.append(setToString(in));
		sb.append("\\n");
		
		sb.append(ir.toString());
		sb.append("\\n");

		sb.append("Out: ");
		sb.append(setToString(out));

		return sb.toString();
	}
	
	private <T> String setToString(Set<T> set) {
		StringBuilder sb = new StringBuilder();
		sb.append('{');
		
		String elems = set.stream()
			.map(Object::toString)
			.collect(Collectors.joining(","));

		sb.append(elems);

		sb.append('}');
		
		return sb.toString();
	}
	
	public static class ReachingData {
		Set<ReachingDefn> in;
		Set<ReachingDefn> out;
		
		public ReachingData() {
			in = SetUtils.empty();
			out = SetUtils.empty();
		}

		public Set<ReachingDefn> getIn() {
			return in;
		}

		public void setIn(Set<ReachingDefn> in) {
			this.in = in;
		}

		public Set<ReachingDefn> getOut() {
			return out;
		}

		public void setOut(Set<ReachingDefn> out) {
			this.out = out;
		}
	}

	public static class ReachingDefn {
		IRTemp x;
		IRTemp y;
		Node definer;
		
		// Node n defines x = y
		public ReachingDefn(IRTemp x, IRTemp y, Node definer) {
			this.x = x;
			this.y = y;
			this.definer = definer;
		}
		
		public Node getDefiner() {
			return definer;
		}
		public void setDefiner(Node definer) {
			this.definer = definer;
		}
		
		public IRTemp getX() {
			return x;
		}

		public void setX(IRTemp x) {
			this.x = x;
		}

		public IRTemp getY() {
			return y;
		}

		public void setY(IRTemp y) {
			this.y = y;
		}

		public String toString() {
			return definer.getNodeId() + "";
		}

		@Override
		public int hashCode() {
			final int prime = 31;
			int result = 1;
			result = prime * result + ((definer == null) ? 0 : definer.hashCode());
			result = prime * result + ((x == null) ? 0 : x.hashCode());
			result = prime * result + ((y == null) ? 0 : y.hashCode());
			return result;
		}

		@Override
		public boolean equals(Object obj) {
			if (this == obj)
				return true;
			if (obj == null)
				return false;
			if (getClass() != obj.getClass())
				return false;
			ReachingDefn other = (ReachingDefn) obj;
			if (definer == null) {
				if (other.definer != null)
					return false;
			} else if (!definer.equals(other.definer))
				return false;
			if (x == null) {
				if (other.x != null)
					return false;
			} else if (!x.equals(other.x))
				return false;
			if (y == null) {
				if (other.y != null)
					return false;
			} else if (!y.equals(other.y))
				return false;
			return true;
		}
	}
}
